apiVersion: v1
kind: Service
metadata:
  name: scraper-service-app
  namespace: scraper-service-app
spec:
  selector:
    app: scraper-service-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: gunicorn